# Generated by Django 6.0.1 on 2026-01-27 19:08







import django.db.models.deletion  # Importa django.db.models.deletion.



from django.conf import settings  # Importa settings desde `django.conf`.



from django.db import migrations, models  # Importa migrations, models desde `django.db`.











class Migration(migrations.Migration):  # Define la clase `Migration`.







    initial = True  # Asigna un valor a `initial`.







    dependencies = [  # Asigna un valor a `dependencies`.



        migrations.swappable_dependency(settings.AUTH_USER_MODEL),  # Ejecuta `migrations.swappable_dependency`.



    ]  # Cierra el bloque/estructura.







    operations = [  # Asigna un valor a `operations`.



        migrations.CreateModel(  # Ejecuta `migrations.CreateModel`.



            name='Product',  # Asigna un valor a `name`.



            fields=[  # Asigna un valor a `fields`.



                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # Declara el campo `id` en la migracion/definicion.



                ('name', models.CharField(max_length=100)),  # Declara el campo `name` en la migracion/definicion.



                ('price', models.DecimalField(decimal_places=2, max_digits=8)),  # Declara el campo `price` en la migracion/definicion.



                ('stock', models.IntegerField()),  # Declara el campo `stock` en la migracion/definicion.



                ('image', models.URLField(blank=True)),  # Declara el campo `image` en la migracion/definicion.



            ],  # Cierra el bloque/estructura.



        ),  # Cierra el bloque/estructura.



        migrations.CreateModel(  # Ejecuta `migrations.CreateModel`.



            name='Cart',  # Asigna un valor a `name`.



            fields=[  # Asigna un valor a `fields`.



                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # Declara el campo `id` en la migracion/definicion.



                ('quantity', models.IntegerField(default=1)),  # Declara el campo `quantity` en la migracion/definicion.



                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),  # Declara el campo `user` en la migracion/definicion.



                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),  # Declara el campo `product` en la migracion/definicion.



            ],  # Cierra el bloque/estructura.



        ),  # Cierra el bloque/estructura.



    ]  # Cierra el bloque/estructura.



