# Generated by Django 6.0.1 on 2026-01-27 19:08

import django.db.models.deletion  # comentario
from django.conf import settings  # comentario
from django.db import migrations, models  # comentario


class Migration(migrations.Migration):  # comentario

    initial = True  # comentario

    dependencies = [  # comentario
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),  # comentario
    ]  # comentario

    operations = [  # comentario
        migrations.CreateModel(  # comentario
            name='Product',  # comentario
            fields=[  # comentario
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # comentario
                ('name', models.CharField(max_length=100)),  # comentario
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),  # comentario
                ('stock', models.IntegerField()),  # comentario
                ('image', models.URLField(blank=True)),  # comentario
            ],  # comentario
        ),  # comentario
        migrations.CreateModel(  # comentario
            name='Cart',  # comentario
            fields=[  # comentario
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # comentario
                ('quantity', models.IntegerField(default=1)),  # comentario
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),  # comentario
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),  # comentario
            ],  # comentario
        ),  # comentario
    ]  # comentario
