# Generated by Django 6.0.1 on 2026-02-15 16:12







import django.db.models.deletion  # Importa django.db.models.deletion.



from django.conf import settings  # Importa settings desde `django.conf`.



from django.db import migrations, models  # Importa migrations, models desde `django.db`.











class Migration(migrations.Migration):  # Define la clase `Migration`.







    dependencies = [  # Asigna un valor a `dependencies`.



        ('app', '0001_initial'),  # Agrega la tupla `app` a la estructura.



        migrations.swappable_dependency(settings.AUTH_USER_MODEL),  # Ejecuta `migrations.swappable_dependency`.



    ]  # Cierra el bloque/estructura.







    operations = [  # Asigna un valor a `operations`.



        migrations.CreateModel(  # Ejecuta `migrations.CreateModel`.



            name='UserProfile',  # Asigna un valor a `name`.



            fields=[  # Asigna un valor a `fields`.



                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # Declara el campo `id` en la migracion/definicion.



                ('phone', models.CharField(blank=True, max_length=20)),  # Declara el campo `phone` en la migracion/definicion.



                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),  # Declara el campo `user` en la migracion/definicion.



            ],  # Cierra el bloque/estructura.



        ),  # Cierra el bloque/estructura.



    ]  # Cierra el bloque/estructura.



