# Generated by Django 6.0.1 on 2026-02-16 00:00

from django.db import migrations, models  # comentario


class Migration(migrations.Migration):  # comentario

    dependencies = [  # comentario
        ('app', '0003_userprofile_address'),  # comentario
    ]  # comentario

    operations = [  # comentario
        migrations.AlterField(  # comentario
            model_name='product',  # comentario
            name='image',  # comentario
            field=models.ImageField(blank=True, null=True, upload_to='products/'),  # comentario
        ),  # comentario
    ]  # comentario
