# Generated by Django 6.0.1 on 2026-02-16 00:00

from django.db import migrations, models  # Importa migrations, models desde `django.db`.


class Migration(migrations.Migration):  # Define la clase `Migration`.

    dependencies = [  # Asigna un valor a `dependencies`.
        ('app', '0003_userprofile_address'),  # Agrega la tupla `app` a la estructura.
    ]  # Cierra el bloque/estructura.

    operations = [  # Asigna un valor a `operations`.
        migrations.AlterField(  # Ejecuta `migrations.AlterField`.
            model_name='product',  # Asigna un valor a `model_name`.
            name='image',  # Asigna un valor a `name`.
            field=models.ImageField(blank=True, null=True, upload_to='products/'),  # Asigna a `field` un campo `ImageField`.
        ),  # Cierra el bloque/estructura.
    ]  # Cierra el bloque/estructura.
