# Generated by Django 6.0.1 on 2026-02-16 00:00

from django.db import migrations, models  # Importa migrations, models desde `django.db`.
import django.db.models.deletion  # Importa django.db.models.deletion.


DEFAULT_CATEGORIES = [  # Asigna un valor a `DEFAULT_CATEGORIES`.
    ('Trufas', 1),  # Agrega la tupla `Trufas` a la estructura.
    ('Barras', 2),  # Agrega la tupla `Barras` a la estructura.
    ('Regalos', 3),  # Agrega la tupla `Regalos` a la estructura.
    ('Cacao', 4),  # Agrega la tupla `Cacao` a la estructura.
    ('Promociones', 5),  # Agrega la tupla `Promociones` a la estructura.
]  # Cierra el bloque/estructura.


def create_default_categories(apps, schema_editor):  # Define la funcion `create_default_categories`.
    Category = apps.get_model('app', 'Category')  # Asigna a `Category` el resultado de `apps.get_model`.
    for name, order in DEFAULT_CATEGORIES:  # Itera en un bucle `for`.
        Category.objects.get_or_create(name=name, defaults={'order': order})  # Ejecuta `Category.objects.get_or_create`.


def delete_default_categories(apps, schema_editor):  # Define la funcion `delete_default_categories`.
    Category = apps.get_model('app', 'Category')  # Asigna a `Category` el resultado de `apps.get_model`.
    Category.objects.filter(name__in=[name for name, _ in DEFAULT_CATEGORIES]).delete()  # Ejecuta `Category.objects.filter`.


class Migration(migrations.Migration):  # Define la clase `Migration`.

    dependencies = [  # Asigna un valor a `dependencies`.
        ('app', '0004_alter_product_image'),  # Agrega la tupla `app` a la estructura.
    ]  # Cierra el bloque/estructura.

    operations = [  # Asigna un valor a `operations`.
        migrations.CreateModel(  # Ejecuta `migrations.CreateModel`.
            name='Category',  # Asigna un valor a `name`.
            fields=[  # Asigna un valor a `fields`.
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # Declara el campo `id` en la migracion/definicion.
                ('name', models.CharField(max_length=100, unique=True)),  # Declara el campo `name` en la migracion/definicion.
                ('order', models.PositiveIntegerField(default=0)),  # Declara el campo `order` en la migracion/definicion.
            ],  # Cierra el bloque/estructura.
            options={  # Asigna un valor a `options`.
                'ordering': ['order', 'name'],  # Asigna la clave `ordering` con una lista.
            },  # Cierra el bloque/estructura.
        ),  # Cierra el bloque/estructura.
        migrations.AddField(  # Ejecuta `migrations.AddField`.
            model_name='product',  # Asigna un valor a `model_name`.
            name='category',  # Asigna un valor a `name`.
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='app.category'),  # Asigna a `field` un campo `ForeignKey`.
        ),  # Cierra el bloque/estructura.
        migrations.RunPython(create_default_categories, delete_default_categories),  # Ejecuta `migrations.RunPython`.
    ]  # Cierra el bloque/estructura.
