# Generated by Django 6.0.1 on 2026-02-16 00:00

from django.db import migrations, models
import django.db.models.deletion


DEFAULT_CATEGORIES = [
    ('Trufas', 1),
    ('Barras', 2),
    ('Regalos', 3),
    ('Cacao', 4),
    ('Promociones', 5),
]


def create_default_categories(apps, schema_editor):
    Category = apps.get_model('app', 'Category')
    for name, order in DEFAULT_CATEGORIES:
        Category.objects.get_or_create(name=name, defaults={'order': order})


def delete_default_categories(apps, schema_editor):
    Category = apps.get_model('app', 'Category')
    Category.objects.filter(name__in=[name for name, _ in DEFAULT_CATEGORIES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='app.category'),
        ),
        migrations.RunPython(create_default_categories, delete_default_categories),
    ]
