# Generated by Django 6.0.1 on 2026-02-16 00:00

from django.db import migrations, models  # comentario
import django.db.models.deletion  # comentario


DEFAULT_CATEGORIES = [  # comentario
    ('Trufas', 1),  # comentario
    ('Barras', 2),  # comentario
    ('Regalos', 3),  # comentario
    ('Cacao', 4),  # comentario
    ('Promociones', 5),  # comentario
]  # comentario


def create_default_categories(apps, schema_editor):  # comentario
    Category = apps.get_model('app', 'Category')  # comentario
    for name, order in DEFAULT_CATEGORIES:  # comentario
        Category.objects.get_or_create(name=name, defaults={'order': order})  # comentario


def delete_default_categories(apps, schema_editor):  # comentario
    Category = apps.get_model('app', 'Category')  # comentario
    Category.objects.filter(name__in=[name for name, _ in DEFAULT_CATEGORIES]).delete()  # comentario


class Migration(migrations.Migration):  # comentario

    dependencies = [  # comentario
        ('app', '0004_alter_product_image'),  # comentario
    ]  # comentario

    operations = [  # comentario
        migrations.CreateModel(  # comentario
            name='Category',  # comentario
            fields=[  # comentario
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # comentario
                ('name', models.CharField(max_length=100, unique=True)),  # comentario
                ('order', models.PositiveIntegerField(default=0)),  # comentario
            ],  # comentario
            options={  # comentario
                'ordering': ['order', 'name'],  # comentario
            },  # comentario
        ),  # comentario
        migrations.AddField(  # comentario
            model_name='product',  # comentario
            name='category',  # comentario
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='app.category'),  # comentario
        ),  # comentario
        migrations.RunPython(create_default_categories, delete_default_categories),  # comentario
    ]  # comentario
