# Generated by Django 6.0.1 on 2026-02-16 00:00

from django.db import migrations, models  # comentario


class Migration(migrations.Migration):  # comentario

    dependencies = [  # comentario
        ('app', '0005_category_and_product_category'),  # comentario
    ]  # comentario

    operations = [  # comentario
        migrations.AddField(  # comentario
            model_name='category',  # comentario
            name='image',  # comentario
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),  # comentario
        ),  # comentario
    ]  # comentario
