# Generated by Django 6.0.1 on 2026-02-16 00:00

from django.db import migrations, models  # comentario


class Migration(migrations.Migration):  # comentario

    dependencies = [  # comentario
        ('app', '0006_category_image'),  # comentario
    ]  # comentario

    operations = [  # comentario
        migrations.CreateModel(  # comentario
            name='Banner',  # comentario
            fields=[  # comentario
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # comentario
                ('title', models.CharField(blank=True, max_length=120)),  # comentario
                ('image', models.ImageField(upload_to='banners/')),  # comentario
                ('order', models.PositiveIntegerField(default=0)),  # comentario
                ('is_active', models.BooleanField(default=True)),  # comentario
            ],  # comentario
            options={  # comentario
                'ordering': ['order', 'id'],  # comentario
            },  # comentario
        ),  # comentario
    ]  # comentario
