# Generated by Django 6.0.1 on 2026-02-16 00:00

from django.db import migrations, models  # Importa migrations, models desde `django.db`.


class Migration(migrations.Migration):  # Define la clase `Migration`.

    dependencies = [  # Asigna un valor a `dependencies`.
        ('app', '0006_category_image'),  # Agrega la tupla `app` a la estructura.
    ]  # Cierra el bloque/estructura.

    operations = [  # Asigna un valor a `operations`.
        migrations.CreateModel(  # Ejecuta `migrations.CreateModel`.
            name='Banner',  # Asigna un valor a `name`.
            fields=[  # Asigna un valor a `fields`.
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # Declara el campo `id` en la migracion/definicion.
                ('title', models.CharField(blank=True, max_length=120)),  # Declara el campo `title` en la migracion/definicion.
                ('image', models.ImageField(upload_to='banners/')),  # Declara el campo `image` en la migracion/definicion.
                ('order', models.PositiveIntegerField(default=0)),  # Declara el campo `order` en la migracion/definicion.
                ('is_active', models.BooleanField(default=True)),  # Declara el campo `is_active` en la migracion/definicion.
            ],  # Cierra el bloque/estructura.
            options={  # Asigna un valor a `options`.
                'ordering': ['order', 'id'],  # Asigna la clave `ordering` con una lista.
            },  # Cierra el bloque/estructura.
        ),  # Cierra el bloque/estructura.
    ]  # Cierra el bloque/estructura.
