# Generated by Django 6.0.1 on 2026-02-16 12:41

import django.db.models.deletion  # comentario
from django.conf import settings  # comentario
from django.db import migrations, models  # comentario


class Migration(migrations.Migration):  # comentario

    dependencies = [  # comentario
        ('app', '0007_banner'),  # comentario
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),  # comentario
    ]  # comentario

    operations = [  # comentario
        migrations.CreateModel(  # comentario
            name='DeliveryAddress',  # comentario
            fields=[  # comentario
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # comentario
                ('main_address', models.CharField(max_length=255)),  # comentario
                ('secondary_street', models.CharField(blank=True, max_length=255)),  # comentario
                ('apartment', models.CharField(blank=True, max_length=120)),  # comentario
                ('city', models.CharField(max_length=120)),  # comentario
                ('delivery_instructions', models.TextField(blank=True)),  # comentario
                ('is_default', models.BooleanField(default=False)),  # comentario
                ('created_at', models.DateTimeField(auto_now_add=True)),  # comentario
                ('updated_at', models.DateTimeField(auto_now=True)),  # comentario
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_addresses', to=settings.AUTH_USER_MODEL)),  # comentario
            ],  # comentario
            options={  # comentario
                'ordering': ['-is_default', '-id'],  # comentario
            },  # comentario
        ),  # comentario
    ]  # comentario
