# Generated by Django 6.0.1 on 2026-02-16 12:41







import django.db.models.deletion  # Importa django.db.models.deletion.



from django.conf import settings  # Importa settings desde `django.conf`.



from django.db import migrations, models  # Importa migrations, models desde `django.db`.











class Migration(migrations.Migration):  # Define la clase `Migration`.







    dependencies = [  # Asigna un valor a `dependencies`.



        ('app', '0007_banner'),  # Agrega la tupla `app` a la estructura.



        migrations.swappable_dependency(settings.AUTH_USER_MODEL),  # Ejecuta `migrations.swappable_dependency`.



    ]  # Cierra el bloque/estructura.







    operations = [  # Asigna un valor a `operations`.



        migrations.CreateModel(  # Ejecuta `migrations.CreateModel`.



            name='DeliveryAddress',  # Asigna un valor a `name`.



            fields=[  # Asigna un valor a `fields`.



                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # Declara el campo `id` en la migracion/definicion.



                ('main_address', models.CharField(max_length=255)),  # Declara el campo `main_address` en la migracion/definicion.



                ('secondary_street', models.CharField(blank=True, max_length=255)),  # Declara el campo `secondary_street` en la migracion/definicion.



                ('apartment', models.CharField(blank=True, max_length=120)),  # Declara el campo `apartment` en la migracion/definicion.



                ('city', models.CharField(max_length=120)),  # Declara el campo `city` en la migracion/definicion.



                ('delivery_instructions', models.TextField(blank=True)),  # Declara el campo `delivery_instructions` en la migracion/definicion.



                ('is_default', models.BooleanField(default=False)),  # Declara el campo `is_default` en la migracion/definicion.



                ('created_at', models.DateTimeField(auto_now_add=True)),  # Declara el campo `created_at` en la migracion/definicion.



                ('updated_at', models.DateTimeField(auto_now=True)),  # Declara el campo `updated_at` en la migracion/definicion.



                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_addresses', to=settings.AUTH_USER_MODEL)),  # Declara el campo `user` en la migracion/definicion.



            ],  # Cierra el bloque/estructura.



            options={  # Asigna un valor a `options`.



                'ordering': ['-is_default', '-id'],  # Asigna la clave `ordering` con una lista.



            },  # Cierra el bloque/estructura.



        ),  # Cierra el bloque/estructura.



    ]  # Cierra el bloque/estructura.



