# Generated by Django 6.0.1 on 2026-02-16 14:20







import django.db.models.deletion  # Importa django.db.models.deletion.



from django.conf import settings  # Importa settings desde `django.conf`.



from django.db import migrations, models  # Importa migrations, models desde `django.db`.











class Migration(migrations.Migration):  # Define la clase `Migration`.







    dependencies = [  # Asigna un valor a `dependencies`.



        ('app', '0008_deliveryaddress'),  # Agrega la tupla `app` a la estructura.



        migrations.swappable_dependency(settings.AUTH_USER_MODEL),  # Ejecuta `migrations.swappable_dependency`.



    ]  # Cierra el bloque/estructura.







    operations = [  # Asigna un valor a `operations`.



        migrations.CreateModel(  # Ejecuta `migrations.CreateModel`.



            name='RoleChangeRequest',  # Asigna un valor a `name`.



            fields=[  # Asigna un valor a `fields`.



                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # Declara el campo `id` en la migracion/definicion.



                ('requested_role', models.CharField(choices=[('provider', 'Proveedor'), ('driver', 'Repartidor')], max_length=20)),  # Declara el campo `requested_role` en la migracion/definicion.



                ('reason', models.TextField(blank=True)),  # Declara el campo `reason` en la migracion/definicion.



                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=20)),  # Declara el campo `status` en la migracion/definicion.



                ('created_at', models.DateTimeField(auto_now_add=True)),  # Declara el campo `created_at` en la migracion/definicion.



                ('updated_at', models.DateTimeField(auto_now=True)),  # Declara el campo `updated_at` en la migracion/definicion.



                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_change_requests', to=settings.AUTH_USER_MODEL)),  # Declara el campo `user` en la migracion/definicion.



            ],  # Cierra el bloque/estructura.



            options={  # Asigna un valor a `options`.



                'ordering': ['-id'],  # Asigna la clave `ordering` con una lista.



            },  # Cierra el bloque/estructura.



        ),  # Cierra el bloque/estructura.



    ]  # Cierra el bloque/estructura.



