# Generated by Django 6.0.1 on 2026-02-16 14:20

import django.db.models.deletion  # comentario
from django.conf import settings  # comentario
from django.db import migrations, models  # comentario


class Migration(migrations.Migration):  # comentario

    dependencies = [  # comentario
        ('app', '0008_deliveryaddress'),  # comentario
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),  # comentario
    ]  # comentario

    operations = [  # comentario
        migrations.CreateModel(  # comentario
            name='RoleChangeRequest',  # comentario
            fields=[  # comentario
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # comentario
                ('requested_role', models.CharField(choices=[('provider', 'Proveedor'), ('driver', 'Repartidor')], max_length=20)),  # comentario
                ('reason', models.TextField(blank=True)),  # comentario
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=20)),  # comentario
                ('created_at', models.DateTimeField(auto_now_add=True)),  # comentario
                ('updated_at', models.DateTimeField(auto_now=True)),  # comentario
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_change_requests', to=settings.AUTH_USER_MODEL)),  # comentario
            ],  # comentario
            options={  # comentario
                'ordering': ['-id'],  # comentario
            },  # comentario
        ),  # comentario
    ]  # comentario
