# Generated by Django 6.0.1 on 2026-02-16 15:53

from django.db import migrations, models  # comentario


class Migration(migrations.Migration):  # comentario

    dependencies = [  # comentario
        ('app', '0009_rolechangerequest'),  # comentario
    ]  # comentario

    operations = [  # comentario
        migrations.AddField(  # comentario
            model_name='product',  # comentario
            name='description',  # comentario
            field=models.TextField(blank=True),  # comentario
        ),  # comentario
        migrations.AddField(  # comentario
            model_name='product',  # comentario
            name='old_price',  # comentario
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),  # comentario
        ),  # comentario
        migrations.AddField(  # comentario
            model_name='product',  # comentario
            name='rating',  # comentario
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),  # comentario
        ),  # comentario
        migrations.AddField(  # comentario
            model_name='product',  # comentario
            name='reviews_count',  # comentario
            field=models.PositiveIntegerField(default=0),  # comentario
        ),  # comentario
        migrations.AddField(  # comentario
            model_name='product',  # comentario
            name='store_name',  # comentario
            field=models.CharField(blank=True, max_length=120),  # comentario
        ),  # comentario
    ]  # comentario
