# Generated by Django 6.0.1 on 2026-02-16 15:53







from django.db import migrations, models  # Importa migrations, models desde `django.db`.











class Migration(migrations.Migration):  # Define la clase `Migration`.







    dependencies = [  # Asigna un valor a `dependencies`.



        ('app', '0009_rolechangerequest'),  # Agrega la tupla `app` a la estructura.



    ]  # Cierra el bloque/estructura.







    operations = [  # Asigna un valor a `operations`.



        migrations.AddField(  # Ejecuta `migrations.AddField`.



            model_name='product',  # Asigna un valor a `model_name`.



            name='description',  # Asigna un valor a `name`.



            field=models.TextField(blank=True),  # Asigna a `field` un campo `TextField`.



        ),  # Cierra el bloque/estructura.



        migrations.AddField(  # Ejecuta `migrations.AddField`.



            model_name='product',  # Asigna un valor a `model_name`.



            name='old_price',  # Asigna un valor a `name`.



            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),  # Asigna a `field` un campo `DecimalField`.



        ),  # Cierra el bloque/estructura.



        migrations.AddField(  # Ejecuta `migrations.AddField`.



            model_name='product',  # Asigna un valor a `model_name`.



            name='rating',  # Asigna un valor a `name`.



            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),  # Asigna a `field` un campo `DecimalField`.



        ),  # Cierra el bloque/estructura.



        migrations.AddField(  # Ejecuta `migrations.AddField`.



            model_name='product',  # Asigna un valor a `model_name`.



            name='reviews_count',  # Asigna un valor a `name`.



            field=models.PositiveIntegerField(default=0),  # Asigna a `field` un campo `PositiveIntegerField`.



        ),  # Cierra el bloque/estructura.



        migrations.AddField(  # Ejecuta `migrations.AddField`.



            model_name='product',  # Asigna un valor a `model_name`.



            name='store_name',  # Asigna un valor a `name`.



            field=models.CharField(blank=True, max_length=120),  # Asigna a `field` un campo `CharField`.



        ),  # Cierra el bloque/estructura.



    ]  # Cierra el bloque/estructura.



