# Generated by Django 6.0.1 on 2026-02-18 00:00

import django.db.models.deletion  # comentario
from django.conf import settings  # comentario
from django.db import migrations, models  # comentario


class Migration(migrations.Migration):  # comentario

    dependencies = [  # comentario
        ('app', '0010_product_description_product_old_price_product_rating_and_more'),  # comentario
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),  # comentario
    ]  # comentario

    operations = [  # comentario
        migrations.CreateModel(  # comentario
            name='Order',  # comentario
            fields=[  # comentario
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # comentario
                ('delivery_main_address', models.CharField(max_length=255)),  # comentario
                ('delivery_secondary_street', models.CharField(blank=True, max_length=255)),  # comentario
                ('delivery_apartment', models.CharField(blank=True, max_length=120)),  # comentario
                ('delivery_city', models.CharField(max_length=120)),  # comentario
                ('delivery_instructions', models.TextField(blank=True)),  # comentario
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('preparing', 'En preparacion'), ('on_the_way', 'En camino'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),  # comentario
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),  # comentario
                ('total_items', models.PositiveIntegerField(default=0)),  # comentario
                ('created_at', models.DateTimeField(auto_now_add=True)),  # comentario
                ('updated_at', models.DateTimeField(auto_now=True)),  # comentario
                ('delivery_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='app.deliveryaddress')),  # comentario
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),  # comentario
            ],  # comentario
            options={  # comentario
                'ordering': ['-id'],  # comentario
            },  # comentario
        ),  # comentario
        migrations.CreateModel(  # comentario
            name='OrderItem',  # comentario
            fields=[  # comentario
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # comentario
                ('product_name', models.CharField(max_length=100)),  # comentario
                ('product_price', models.DecimalField(decimal_places=2, max_digits=8)),  # comentario
                ('quantity', models.PositiveIntegerField(default=1)),  # comentario
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),  # comentario
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.order')),  # comentario
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='app.product')),  # comentario
            ],  # comentario
            options={  # comentario
                'ordering': ['id'],  # comentario
            },  # comentario
        ),  # comentario
    ]  # comentario
