# Generated by Django 6.0.1 on 2026-02-18 00:00

import django.db.models.deletion  # Importa django.db.models.deletion.
from django.conf import settings  # Importa settings desde `django.conf`.
from django.db import migrations, models  # Importa migrations, models desde `django.db`.


class Migration(migrations.Migration):  # Define la clase `Migration`.

    dependencies = [  # Asigna un valor a `dependencies`.
        ('app', '0010_product_description_product_old_price_product_rating_and_more'),  # Agrega la tupla `app` a la estructura.
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),  # Ejecuta `migrations.swappable_dependency`.
    ]  # Cierra el bloque/estructura.

    operations = [  # Asigna un valor a `operations`.
        migrations.CreateModel(  # Ejecuta `migrations.CreateModel`.
            name='Order',  # Asigna un valor a `name`.
            fields=[  # Asigna un valor a `fields`.
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # Declara el campo `id` en la migracion/definicion.
                ('delivery_main_address', models.CharField(max_length=255)),  # Declara el campo `delivery_main_address` en la migracion/definicion.
                ('delivery_secondary_street', models.CharField(blank=True, max_length=255)),  # Declara el campo `delivery_secondary_street` en la migracion/definicion.
                ('delivery_apartment', models.CharField(blank=True, max_length=120)),  # Declara el campo `delivery_apartment` en la migracion/definicion.
                ('delivery_city', models.CharField(max_length=120)),  # Declara el campo `delivery_city` en la migracion/definicion.
                ('delivery_instructions', models.TextField(blank=True)),  # Declara el campo `delivery_instructions` en la migracion/definicion.
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('preparing', 'En preparacion'), ('on_the_way', 'En camino'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),  # Declara el campo `status` en la migracion/definicion.
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),  # Declara el campo `total_amount` en la migracion/definicion.
                ('total_items', models.PositiveIntegerField(default=0)),  # Declara el campo `total_items` en la migracion/definicion.
                ('created_at', models.DateTimeField(auto_now_add=True)),  # Declara el campo `created_at` en la migracion/definicion.
                ('updated_at', models.DateTimeField(auto_now=True)),  # Declara el campo `updated_at` en la migracion/definicion.
                ('delivery_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='app.deliveryaddress')),  # Declara el campo `delivery_address` en la migracion/definicion.
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),  # Declara el campo `user` en la migracion/definicion.
            ],  # Cierra el bloque/estructura.
            options={  # Asigna un valor a `options`.
                'ordering': ['-id'],  # Asigna la clave `ordering` con una lista.
            },  # Cierra el bloque/estructura.
        ),  # Cierra el bloque/estructura.
        migrations.CreateModel(  # Ejecuta `migrations.CreateModel`.
            name='OrderItem',  # Asigna un valor a `name`.
            fields=[  # Asigna un valor a `fields`.
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # Declara el campo `id` en la migracion/definicion.
                ('product_name', models.CharField(max_length=100)),  # Declara el campo `product_name` en la migracion/definicion.
                ('product_price', models.DecimalField(decimal_places=2, max_digits=8)),  # Declara el campo `product_price` en la migracion/definicion.
                ('quantity', models.PositiveIntegerField(default=1)),  # Declara el campo `quantity` en la migracion/definicion.
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),  # Declara el campo `subtotal` en la migracion/definicion.
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.order')),  # Declara el campo `order` en la migracion/definicion.
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='app.product')),  # Declara el campo `product` en la migracion/definicion.
            ],  # Cierra el bloque/estructura.
            options={  # Asigna un valor a `options`.
                'ordering': ['id'],  # Asigna la clave `ordering` con una lista.
            },  # Cierra el bloque/estructura.
        ),  # Cierra el bloque/estructura.
    ]  # Cierra el bloque/estructura.
