# Generated by Django 6.0.1 on 2026-02-18 00:10

import django.db.models.deletion  # Importa django.db.models.deletion.
from django.conf import settings  # Importa settings desde `django.conf`.
from django.db import migrations, models  # Importa migrations, models desde `django.db`.


class Migration(migrations.Migration):  # Define la clase `Migration`.

    dependencies = [  # Asigna un valor a `dependencies`.
        ('app', '0011_order_and_orderitem'),  # Agrega la tupla `app` a la estructura.
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),  # Ejecuta `migrations.swappable_dependency`.
    ]  # Cierra el bloque/estructura.

    operations = [  # Asigna un valor a `operations`.
        migrations.CreateModel(  # Ejecuta `migrations.CreateModel`.
            name='Shipment',  # Asigna un valor a `name`.
            fields=[  # Asigna un valor a `fields`.
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # Declara el campo `id` en la migracion/definicion.
                ('status', models.CharField(choices=[('pending_assignment', 'Pendiente de asignacion'), ('assigned', 'Asignado'), ('picked_up', 'Recogido'), ('on_the_way', 'En camino'), ('nearby', 'Cerca del destino'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending_assignment', max_length=30)),  # Declara el campo `status` en la migracion/definicion.
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),  # Declara el campo `current_latitude` en la migracion/definicion.
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),  # Declara el campo `current_longitude` en la migracion/definicion.
                ('current_heading', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),  # Declara el campo `current_heading` en la migracion/definicion.
                ('current_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),  # Declara el campo `current_speed` en la migracion/definicion.
                ('last_location_at', models.DateTimeField(blank=True, null=True)),  # Declara el campo `last_location_at` en la migracion/definicion.
                ('eta_minutes', models.PositiveIntegerField(blank=True, null=True)),  # Declara el campo `eta_minutes` en la migracion/definicion.
                ('notes', models.CharField(blank=True, max_length=255)),  # Declara el campo `notes` en la migracion/definicion.
                ('created_at', models.DateTimeField(auto_now_add=True)),  # Declara el campo `created_at` en la migracion/definicion.
                ('updated_at', models.DateTimeField(auto_now=True)),  # Declara el campo `updated_at` en la migracion/definicion.
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_assigned', to=settings.AUTH_USER_MODEL)),  # Declara el campo `driver` en la migracion/definicion.
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='app.order')),  # Declara el campo `order` en la migracion/definicion.
            ],  # Cierra el bloque/estructura.
            options={  # Asigna un valor a `options`.
                'ordering': ['-id'],  # Asigna la clave `ordering` con una lista.
            },  # Cierra el bloque/estructura.
        ),  # Cierra el bloque/estructura.
        migrations.CreateModel(  # Ejecuta `migrations.CreateModel`.
            name='ShipmentLocation',  # Asigna un valor a `name`.
            fields=[  # Asigna un valor a `fields`.
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # Declara el campo `id` en la migracion/definicion.
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),  # Declara el campo `latitude` en la migracion/definicion.
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),  # Declara el campo `longitude` en la migracion/definicion.
                ('heading', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),  # Declara el campo `heading` en la migracion/definicion.
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),  # Declara el campo `speed` en la migracion/definicion.
                ('recorded_at', models.DateTimeField(auto_now_add=True)),  # Declara el campo `recorded_at` en la migracion/definicion.
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='app.shipment')),  # Declara el campo `shipment` en la migracion/definicion.
            ],  # Cierra el bloque/estructura.
            options={  # Asigna un valor a `options`.
                'ordering': ['-recorded_at', '-id'],  # Asigna la clave `ordering` con una lista.
            },  # Cierra el bloque/estructura.
        ),  # Cierra el bloque/estructura.
    ]  # Cierra el bloque/estructura.
