# Generated by Django 6.0.1 on 2026-02-18 00:10

import django.db.models.deletion  # comentario
from django.conf import settings  # comentario
from django.db import migrations, models  # comentario


class Migration(migrations.Migration):  # comentario

    dependencies = [  # comentario
        ('app', '0011_order_and_orderitem'),  # comentario
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),  # comentario
    ]  # comentario

    operations = [  # comentario
        migrations.CreateModel(  # comentario
            name='Shipment',  # comentario
            fields=[  # comentario
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # comentario
                ('status', models.CharField(choices=[('pending_assignment', 'Pendiente de asignacion'), ('assigned', 'Asignado'), ('picked_up', 'Recogido'), ('on_the_way', 'En camino'), ('nearby', 'Cerca del destino'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending_assignment', max_length=30)),  # comentario
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),  # comentario
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),  # comentario
                ('current_heading', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),  # comentario
                ('current_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),  # comentario
                ('last_location_at', models.DateTimeField(blank=True, null=True)),  # comentario
                ('eta_minutes', models.PositiveIntegerField(blank=True, null=True)),  # comentario
                ('notes', models.CharField(blank=True, max_length=255)),  # comentario
                ('created_at', models.DateTimeField(auto_now_add=True)),  # comentario
                ('updated_at', models.DateTimeField(auto_now=True)),  # comentario
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_assigned', to=settings.AUTH_USER_MODEL)),  # comentario
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='app.order')),  # comentario
            ],  # comentario
            options={  # comentario
                'ordering': ['-id'],  # comentario
            },  # comentario
        ),  # comentario
        migrations.CreateModel(  # comentario
            name='ShipmentLocation',  # comentario
            fields=[  # comentario
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # comentario
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),  # comentario
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),  # comentario
                ('heading', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),  # comentario
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),  # comentario
                ('recorded_at', models.DateTimeField(auto_now_add=True)),  # comentario
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='app.shipment')),  # comentario
            ],  # comentario
            options={  # comentario
                'ordering': ['-recorded_at', '-id'],  # comentario
            },  # comentario
        ),  # comentario
    ]  # comentario
