# Generated by Django 6.0.1 on 2026-03-15 01:22

from django.db import migrations, models  # comentario


class Migration(migrations.Migration):  # comentario

    dependencies = [  # comentario
        ('app', '0012_shipment_and_shipmentlocation'),  # comentario
    ]  # comentario

    operations = [  # comentario
        migrations.AddField(  # comentario
            model_name='userprofile',  # comentario
            name='avatar',  # comentario
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),  # comentario
        ),  # comentario
    ]  # comentario
