# Generated by Django 6.0.1 on 2026-03-15 02:10

from django.db import migrations, models  # Importa migrations, models desde `django.db`.


class Migration(migrations.Migration):  # Define la clase `Migration`.

    dependencies = [  # Asigna un valor a `dependencies`.
        ('app', '0013_userprofile_avatar'),  # Agrega la tupla `app` a la estructura.
    ]  # Cierra el bloque/estructura.

    operations = [  # Asigna un valor a `operations`.
        migrations.AddField(  # Ejecuta `migrations.AddField`.
            model_name='deliveryaddress',  # Asigna un valor a `model_name`.
            name='latitude',  # Asigna un valor a `name`.
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),  # Asigna a `field` un campo `DecimalField`.
        ),  # Cierra el bloque/estructura.
        migrations.AddField(  # Ejecuta `migrations.AddField`.
            model_name='deliveryaddress',  # Asigna un valor a `model_name`.
            name='longitude',  # Asigna un valor a `name`.
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),  # Asigna a `field` un campo `DecimalField`.
        ),  # Cierra el bloque/estructura.
        migrations.AddField(  # Ejecuta `migrations.AddField`.
            model_name='order',  # Asigna un valor a `model_name`.
            name='delivery_latitude',  # Asigna un valor a `name`.
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),  # Asigna a `field` un campo `DecimalField`.
        ),  # Cierra el bloque/estructura.
        migrations.AddField(  # Ejecuta `migrations.AddField`.
            model_name='order',  # Asigna un valor a `model_name`.
            name='delivery_longitude',  # Asigna un valor a `name`.
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),  # Asigna a `field` un campo `DecimalField`.
        ),  # Cierra el bloque/estructura.
    ]  # Cierra el bloque/estructura.

