# Generated by Django 6.0.1 on 2026-03-15 02:10

from django.db import migrations, models  # comentario


class Migration(migrations.Migration):  # comentario

    dependencies = [  # comentario
        ('app', '0013_userprofile_avatar'),  # comentario
    ]  # comentario

    operations = [  # comentario
        migrations.AddField(  # comentario
            model_name='deliveryaddress',  # comentario
            name='latitude',  # comentario
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),  # comentario
        ),  # comentario
        migrations.AddField(  # comentario
            model_name='deliveryaddress',  # comentario
            name='longitude',  # comentario
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),  # comentario
        ),  # comentario
        migrations.AddField(  # comentario
            model_name='order',  # comentario
            name='delivery_latitude',  # comentario
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),  # comentario
        ),  # comentario
        migrations.AddField(  # comentario
            model_name='order',  # comentario
            name='delivery_longitude',  # comentario
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),  # comentario
        ),  # comentario
    ]  # comentario

