# Generated by Django 6.0.1 on 2026-03-20 21:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_deliveryaddress_and_order_coords'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChocolateLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_code', models.CharField(db_index=True, max_length=60, unique=True)),
                ('qr_code', models.CharField(db_index=True, max_length=120, unique=True)),
                ('production_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('cacao_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bean_origin', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='app.product')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CocoaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cacao_variety', models.CharField(blank=True, max_length=120)),
                ('origin_country', models.CharField(blank=True, max_length=120)),
                ('origin_region', models.CharField(blank=True, max_length=120)),
                ('farm_name', models.CharField(blank=True, max_length=160)),
                ('fermentation_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('drying_days', models.PositiveIntegerField(blank=True, null=True)),
                ('roasting_profile', models.CharField(blank=True, max_length=160)),
                ('story', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cocoa_info', to='app.product')),
            ],
            options={
                'ordering': ['product_id'],
            },
        ),
        migrations.CreateModel(
            name='LotTraceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=120)),
                ('status', models.CharField(default='completed', max_length=40)),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app.chocolatelot')),
            ],
            options={
                'ordering': ['event_date', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='chocolatelot',
            index=models.Index(fields=['product', 'is_active'], name='app_chocola_product_1103fd_idx'),
        ),
    ]
